#!/bin/bash

#setting UUID
UUID=$(uuidgen)
sed -i 's,rundeck.server.uuid\s\=\s.*,rundeck.server.uuid\='"${UUID}"',g' "$FWKPROPS"



RUNDECK_AUTORECOVER_ENABLE=${RUNDECK_AUTORECOVER_ENABLE:-true}

# enabling cluster mode
cat >>"$RDPROPS" <<END

rundeck.clusterMode.enabled=true

# heartbeat interval in seconds
rundeck.clusterMode.heartbeat.interval=30

# initial delay after startup to send heartbeat
rundeck.clusterMode.heartbeat.delay=10

# age in seconds since last heartbeat to consider another member inactive
rundeck.clusterMode.heartbeat.considerInactive=150

# age in seconds since last heartbeat to consider another member dead
rundeck.clusterMode.heartbeat.considerDead=300

# Auto Recover
#
# enable auto cleanup of stale jobs on member death
rundeck.clusterMode.recoverExecutions.enabled=$RUNDECK_AUTORECOVER_ENABLE

# policy for members to accept as targets of auto cleanup. Can be 'Any' or 'Static'
# if static, config requires 'allowed' setting
rundeck.clusterMode.recoverExecutions.policy=Any

# configure allowed member UUIDs if using policy 'static'
# rundeck.clusterMode.recoverExecutions.config.allowed=<uuid1>,<uuid2>,...

# delay in seconds before proceeding with autoretry proposal
rundeck.clusterMode.recoverExecutions.delay=60

# delay in seconds before doing another autoretry of the same member
rundeck.clusterMode.recoverExecutions.sleep=180
END


if [[ ! -z "$RUNDECK_REMOTE_POLICY_ENABLE" ]]; then

RUNDECK_REMOTE_DEFAULT_POLICY=${RUNDECK_REMOTE_DEFAULT_POLICY:-Random}
RUNDECK_REMOTE_DEFAULT_ALLOWED=${RUNDECK_REMOTE_DEFAULT_ALLOWED:-other}
RUNDECK_REMOTE_DEFAULT_ALLOWED_TAGS=${RUNDECK_REMOTE_DEFAULT_ALLOWED_TAGS:-worker}
RUNDECK_REMOTE_DEFAULT_PREFERRED_TAGS=${RUNDECK_REMOTE_DEFAULT_PREFERRED_TAGS:-worker}

cat - >>"$RDPROPS" <<END

# remote execute/abort message processing interval in seconds
rundeck.clusterMode.remoteExec.process.interval=5

# Remote Execution policy: Default
rundeck.clusterMode.remoteExecution.policy = $RUNDECK_REMOTE_DEFAULT_POLICY
rundeck.clusterMode.remoteExecution.config.allowed = $RUNDECK_REMOTE_DEFAULT_ALLOWED
rundeck.clusterMode.remoteExecution.config.allowedTags = $RUNDECK_REMOTE_DEFAULT_ALLOWED_TAGS
rundeck.clusterMode.remoteExecution.config.preferredTags = $RUNDECK_REMOTE_DEFAULT_PREFERRED_TAGS
rundeck.clusterMode.remoteExecution.config.activeOnly = true



END

fi


if [ -n "$RUNDECK_SERVER_LABEL" ] ; then
cat >> "$FWKPROPS" <<END
# Server tags
rundeck.server.tags=${RUNDECK_SERVER_LABEL:-}
END
fi
